version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/anglerphish
    depends_on:
      - mongo
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=anglerphish

volumes:
  mongo_data: